name: AOL DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate Python File
        run: |
          python -m py_compile app.py

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: Production

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/aol-devops-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/aol-devops-app:latest
